### ISSUE TITLE
Error Analysis: Key Error for categorical features 

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#530]
Running error analysis on Azure Notebooks. Compute Instance has python 3.6.9. 

ErrorAnalysis started at https://comp-erroranalysis-5000.westus2.instances.azureml.ms
<raiwidgets.error_analysis_dashboard.ErrorAnalysisDashboard at 0x7f176c1359e8>
categorical_feature in Dataset is overridden.
New categorical_feature is [1, 3, 5, 6, 7, 8, 9, 13]
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pandas/core/computation/scope.py", line 188, in resolve
    return self.resolvers[key]
  File "/anaconda/envs/azureml_py36/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/anaconda/envs/azureml_py36/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'education_'

**Comment by romanlutz** [comment]
@nushib @imatiach-msft is there anything else to be done about this issue?
Is there a minimum pandas version we should enforce?

**Comment by imatiach-msft** [comment]
Closing as we now print a warning for older versions of pandas
